package main


import (
 "strings"
 "fmt"
 "flag"
 "github.com/ralfonso-directnic/bayesian"
)

const (

Cat0 bayesian.Class = "Uncategorized"
Cat1 bayesian.Class = "Financial Services"
Cat2 bayesian.Class = "Travel and Lodging"
Cat3 bayesian.Class = "Home and Garden"
Cat4 bayesian.Class = "Computers and Electronics"
Cat5 bayesian.Class = "Arts and Entertainment"
Cat6 bayesian.Class = "Health and Wellness"
Cat7 bayesian.Class = "Business"
Cat8 bayesian.Class = "Vehicles"
Cat9 bayesian.Class = "Clothing and Shoes"
Cat10 bayesian.Class = "Education and Training"
Cat11 bayesian.Class = "Sports and Recreation"
Cat12 bayesian.Class = "Food and Restaurants"
Cat13 bayesian.Class = "Shopping"
Cat14 bayesian.Class = "Real Estate"
Cat15 bayesian.Class = "Families and Relationships"
Cat16 bayesian.Class = "Social Sciences"
Cat17 bayesian.Class = "Society and Culture"
Cat18 bayesian.Class = "Careers and Employment"
Cat19 bayesian.Class = "Beauty and Personal Care"

)

var search string


func toSlice(str string) ([]string){ 

return strings.Split(str," ")

}

func main(){


flag.StringVar(&search,"search","","Keyword to classify")

flag.Parse()

classifier := bayesian.NewClassifierTfIdf(Cat0,Cat1,Cat2,Cat3,Cat4,Cat5,Cat6,Cat7,Cat8,Cat9,Cat10,Cat11,Cat12,Cat13,Cat14,Cat15,Cat16,Cat17,Cat18,Cat19)


classifier.Learn(toSlice("alaska cruises"),Cat2)
classifier.Learn(toSlice("laptop"),Cat4)
classifier.Learn(toSlice("cheap airfare"),Cat2)
classifier.Learn(toSlice("cheap car rental"),Cat2)
classifier.Learn(toSlice("cheap rental cars"),Cat2)
classifier.Learn(toSlice("cheapest flights"),Cat2)
classifier.Learn(toSlice("cruise"),Cat2)
classifier.Learn(toSlice("dollar rental car"),Cat2)
classifier.Learn(toSlice("doordash delivery"),Cat2)
classifier.Learn(toSlice("hertz car sales"),Cat2)
classifier.Learn(toSlice("hotel"),Cat2)
classifier.Learn(toSlice("private jet charter prices"),Cat2)
classifier.Learn(toSlice("rental car"),Cat2)
classifier.Learn(toSlice("rental cars"),Cat2)
classifier.Learn(toSlice("rv rentals"),Cat2)
classifier.Learn(toSlice("venetian las vegas hotel and casino"),Cat2)
classifier.Learn(toSlice("address labels personalized"),Cat3)
classifier.Learn(toSlice("air purifiers"),Cat3)
classifier.Learn(toSlice("air purifiers for home"),Cat3)
classifier.Learn(toSlice("aldi delivery"),Cat3)
classifier.Learn(toSlice("art prints"),Cat3)
classifier.Learn(toSlice("at a glance 2021 calendar"),Cat3)
classifier.Learn(toSlice("at t internet service"),Cat3)
classifier.Learn(toSlice("avocado mattress"),Cat3)
classifier.Learn(toSlice("bathroom faucets"),Cat3)
classifier.Learn(toSlice("bathroom light fixtures"),Cat3)
classifier.Learn(toSlice("bathroom vanities"),Cat3)
classifier.Learn(toSlice("beautyrest mattress"),Cat3)
classifier.Learn(toSlice("best dog food"),Cat3)
classifier.Learn(toSlice("bidet attachment for toilets"),Cat3)
classifier.Learn(toSlice("blink home security system"),Cat3)
classifier.Learn(toSlice("bookshelf"),Cat3)
classifier.Learn(toSlice("cable tv providers in my area"),Cat3)
classifier.Learn(toSlice("canon ink cartridges"),Cat3)
classifier.Learn(toSlice("carpets rugs"),Cat3)
classifier.Learn(toSlice("casper mattress"),Cat3)
classifier.Learn(toSlice("ceiling fans with lights"),Cat3)
classifier.Learn(toSlice("ceiling lights"),Cat3)
classifier.Learn(toSlice("closet organizers"),Cat3)
classifier.Learn(toSlice("cordless vacuum cleaners"),Cat3)
classifier.Learn(toSlice("cowhide rugs"),Cat3)
classifier.Learn(toSlice("day bed"),Cat3)
classifier.Learn(toSlice("delta bathroom faucets"),Cat3)
classifier.Learn(toSlice("desk chair"),Cat3)
classifier.Learn(toSlice("desk lamps"),Cat3)
classifier.Learn(toSlice("disposable gloves"),Cat3)
classifier.Learn(toSlice("dog beds for large dogs"),Cat3)
classifier.Learn(toSlice("dog food"),Cat3)
classifier.Learn(toSlice("dyson cordless vacuum"),Cat3)
classifier.Learn(toSlice("dyson vacuum cleaners"),Cat3)
classifier.Learn(toSlice("fancy feast cat food"),Cat3)
classifier.Learn(toSlice("floor lamps"),Cat3)
classifier.Learn(toSlice("frame"),Cat3)
classifier.Learn(toSlice("framed art"),Cat3)
classifier.Learn(toSlice("frames"),Cat3)
classifier.Learn(toSlice("furnace"),Cat3)
classifier.Learn(toSlice("garage cabinets and storage"),Cat3)
classifier.Learn(toSlice("ge dishwasher parts"),Cat3)
classifier.Learn(toSlice("hand sanitizer"),Cat3)
classifier.Learn(toSlice("hardwood flooring"),Cat3)
classifier.Learn(toSlice("hills prescription diet dog food"),Cat3)
classifier.Learn(toSlice("home depot bathroom vanities"),Cat3)
classifier.Learn(toSlice("indoor outdoor rugs"),Cat3)
classifier.Learn(toSlice("kitchen sinks"),Cat3)
classifier.Learn(toSlice("lamp shades replacements"),Cat3)
classifier.Learn(toSlice("liftmaster garage door opener"),Cat3)
classifier.Learn(toSlice("miele vacuum cleaners"),Cat3)
classifier.Learn(toSlice("mini blinds"),Cat3)
classifier.Learn(toSlice("my pillow promo code buy one get one free"),Cat3)
classifier.Learn(toSlice("nectar mattress"),Cat3)
classifier.Learn(toSlice("parachute bedding"),Cat3)
classifier.Learn(toSlice("pet supplies"),Cat3)
classifier.Learn(toSlice("picture frames"),Cat3)
classifier.Learn(toSlice("pillows"),Cat3)
classifier.Learn(toSlice("polywood outdoor furniture"),Cat3)
classifier.Learn(toSlice("puffy mattress"),Cat3)
classifier.Learn(toSlice("purple mattress"),Cat3)
classifier.Learn(toSlice("reverse osmosis water filter system"),Cat3)
classifier.Learn(toSlice("roller shades for windows"),Cat3)
classifier.Learn(toSlice("room dividers"),Cat3)
classifier.Learn(toSlice("round rugs"),Cat3)
classifier.Learn(toSlice("rubber flooring"),Cat3)
classifier.Learn(toSlice("rugs"),Cat3)
classifier.Learn(toSlice("samsung water filters for refrigerators"),Cat3)
classifier.Learn(toSlice("sauna"),Cat3)
classifier.Learn(toSlice("shelving units"),Cat3)
classifier.Learn(toSlice("sleep number beds"),Cat3)
classifier.Learn(toSlice("tempur-pedic mattress"),Cat3)
classifier.Learn(toSlice("tesla solar roof"),Cat3)
classifier.Learn(toSlice("theater seating"),Cat3)
classifier.Learn(toSlice("toilets"),Cat3)
classifier.Learn(toSlice("traeger grills"),Cat3)
classifier.Learn(toSlice("vanities for bathrooms"),Cat3)
classifier.Learn(toSlice("vertical blinds"),Cat3)
classifier.Learn(toSlice("wayfair rugs"),Cat3)
classifier.Learn(toSlice("whirlpool washer"),Cat3)
classifier.Learn(toSlice("wine coolers refrigerators"),Cat3)
classifier.Learn(toSlice("adt security systems"),Cat4)
classifier.Learn(toSlice("apple ipads"),Cat4)
classifier.Learn(toSlice("apple iphone 12"),Cat4)
classifier.Learn(toSlice("apple iphones"),Cat4)
classifier.Learn(toSlice("cell phone plans"),Cat4)
classifier.Learn(toSlice("desktop computers"),Cat4)
classifier.Learn(toSlice("editing software"),Cat4)
classifier.Learn(toSlice("epson ink"),Cat4)
classifier.Learn(toSlice("flip phones"),Cat4)
classifier.Learn(toSlice("ge appliance parts"),Cat4)
classifier.Learn(toSlice("home security cameras"),Cat4)
classifier.Learn(toSlice("hp 902 ink cartridges"),Cat4)
classifier.Learn(toSlice("ink cartridge replacement"),Cat4)
classifier.Learn(toSlice("iphone 12 colors"),Cat4)
classifier.Learn(toSlice("iphone 12 mini"),Cat4)
classifier.Learn(toSlice("jitterbug cell phones seniors"),Cat4)
classifier.Learn(toSlice("lenovo laptops"),Cat4)
classifier.Learn(toSlice("refrigerator parts"),Cat4)
classifier.Learn(toSlice("samsung earbuds"),Cat4)
classifier.Learn(toSlice("tablet"),Cat4)
classifier.Learn(toSlice("tablets"),Cat4)
classifier.Learn(toSlice("tablets on sale"),Cat4)
classifier.Learn(toSlice("tv online"),Cat4)
classifier.Learn(toSlice("water filters for refrigerators"),Cat4)
classifier.Learn(toSlice("4 ocean face masks"),Cat6)
classifier.Learn(toSlice("best treadmills for home use"),Cat6)
classifier.Learn(toSlice("keto diet"),Cat6)
classifier.Learn(toSlice("keto diet plan for beginners"),Cat6)
classifier.Learn(toSlice("nutrisystem for men"),Cat6)
classifier.Learn(toSlice("nutrisystem for women"),Cat6)
classifier.Learn(toSlice("aeron chair"),Cat7)
classifier.Learn(toSlice("bridal shower invitations"),Cat7)
classifier.Learn(toSlice("calendars"),Cat7)
classifier.Learn(toSlice("digital signature"),Cat7)
classifier.Learn(toSlice("download python"),Cat7)
classifier.Learn(toSlice("free business cards"),Cat7)
classifier.Learn(toSlice("free logo"),Cat7)
classifier.Learn(toSlice("l shaped desk"),Cat7)
classifier.Learn(toSlice("l-shaped office desks"),Cat7)
classifier.Learn(toSlice("moo business cards"),Cat7)
classifier.Learn(toSlice("office chairs"),Cat7)
classifier.Learn(toSlice("office chairs ergonomic"),Cat7)
classifier.Learn(toSlice("office desk"),Cat7)
classifier.Learn(toSlice("office desks for home"),Cat7)
classifier.Learn(toSlice("office supplies"),Cat7)
classifier.Learn(toSlice("python download"),Cat7)
classifier.Learn(toSlice("usps stamps"),Cat7)
classifier.Learn(toSlice("vpn for pc"),Cat7)
classifier.Learn(toSlice("audi q8"),Cat8)
classifier.Learn(toSlice("bmw suv"),Cat8)
classifier.Learn(toSlice("buick enclave"),Cat8)
classifier.Learn(toSlice("buick encore gx"),Cat8)
classifier.Learn(toSlice("car rental"),Cat8)
classifier.Learn(toSlice("car rental companies"),Cat8)
classifier.Learn(toSlice("car seat covers"),Cat8)
classifier.Learn(toSlice("carfax report"),Cat8)
classifier.Learn(toSlice("carhartt seat covers for trucks"),Cat8)
classifier.Learn(toSlice("carvana online car buying"),Cat8)
classifier.Learn(toSlice("chevy colorado "),Cat8)
classifier.Learn(toSlice("chevy equinox"),Cat8)
classifier.Learn(toSlice("chevy tahoe"),Cat8)
classifier.Learn(toSlice("chevy traverse"),Cat8)
classifier.Learn(toSlice("chevy trax"),Cat8)
classifier.Learn(toSlice("dodge durango"),Cat8)
classifier.Learn(toSlice("dodge ram trucks"),Cat8)
classifier.Learn(toSlice("dodge trucks"),Cat8)
classifier.Learn(toSlice("electric cars for sale"),Cat8)
classifier.Learn(toSlice("electric suv"),Cat8)
classifier.Learn(toSlice("ford escape"),Cat8)
classifier.Learn(toSlice("ford expedition"),Cat8)
classifier.Learn(toSlice("ford explorer"),Cat8)
classifier.Learn(toSlice("ford f-150"),Cat8)
classifier.Learn(toSlice("ford f150"),Cat8)
classifier.Learn(toSlice("gmc acadia"),Cat8)
classifier.Learn(toSlice("gmc sierra"),Cat8)
classifier.Learn(toSlice("gmc terrain"),Cat8)
classifier.Learn(toSlice("honda accord"),Cat8)
classifier.Learn(toSlice("honda civic"),Cat8)
classifier.Learn(toSlice("honda crv"),Cat8)
classifier.Learn(toSlice("honda fit"),Cat8)
classifier.Learn(toSlice("honda odyssey"),Cat8)
classifier.Learn(toSlice("honda ridgeline"),Cat8)
classifier.Learn(toSlice("hyundai elantra"),Cat8)
classifier.Learn(toSlice("hyundai kona"),Cat8)
classifier.Learn(toSlice("hyundai palisade"),Cat8)
classifier.Learn(toSlice("hyundai santa fe"),Cat8)
classifier.Learn(toSlice("jeep cherokee"),Cat8)
classifier.Learn(toSlice("jeep compass"),Cat8)
classifier.Learn(toSlice("jeep gladiator"),Cat8)
classifier.Learn(toSlice("jeep grand cherokee"),Cat8)
classifier.Learn(toSlice("jeep wrangler"),Cat8)
classifier.Learn(toSlice("kia k5"),Cat8)
classifier.Learn(toSlice("kia sorento"),Cat8)
classifier.Learn(toSlice("kia sportage"),Cat8)
classifier.Learn(toSlice("kia telluride"),Cat8)
classifier.Learn(toSlice("lexus rx 350"),Cat8)
classifier.Learn(toSlice("mazda cx 5"),Cat8)
classifier.Learn(toSlice("mazda cx-30"),Cat8)
classifier.Learn(toSlice("mazda cx-9"),Cat8)
classifier.Learn(toSlice("mazda cx5"),Cat8)
classifier.Learn(toSlice("mazda cx9"),Cat8)
classifier.Learn(toSlice("mercedes g wagon"),Cat8)
classifier.Learn(toSlice("nissan frontier"),Cat8)
classifier.Learn(toSlice("nissan kicks"),Cat8)
classifier.Learn(toSlice("nissan rogue"),Cat8)
classifier.Learn(toSlice("seat covers for trucks"),Cat8)
classifier.Learn(toSlice("subaru ascent"),Cat8)
classifier.Learn(toSlice("telluride kia suv"),Cat8)
classifier.Learn(toSlice("tires"),Cat8)
classifier.Learn(toSlice("toyota 4 runner "),Cat8)
classifier.Learn(toSlice("toyota c-hr"),Cat8)
classifier.Learn(toSlice("toyota camry"),Cat8)
classifier.Learn(toSlice("toyota highlander"),Cat8)
classifier.Learn(toSlice("toyota rav4"),Cat8)
classifier.Learn(toSlice("toyota rav4 hybrid"),Cat8)
classifier.Learn(toSlice("toyota sale"),Cat8)
classifier.Learn(toSlice("toyota sequoia"),Cat8)
classifier.Learn(toSlice("toyota supra"),Cat8)
classifier.Learn(toSlice("toyota suv models"),Cat8)
classifier.Learn(toSlice("toyota tacoma for sale"),Cat8)
classifier.Learn(toSlice("toyota venza"),Cat8)
classifier.Learn(toSlice("trade-in value for cars"),Cat8)
classifier.Learn(toSlice("trucks for sale"),Cat8)
classifier.Learn(toSlice("u-haul rental"),Cat8)
classifier.Learn(toSlice("used car"),Cat8)
classifier.Learn(toSlice("volkswagen tiguan"),Cat8)
classifier.Learn(toSlice("volvo xc40"),Cat8)
classifier.Learn(toSlice("volvo xc60"),Cat8)
classifier.Learn(toSlice("volvo xc90"),Cat8)
classifier.Learn(toSlice("vrbo rentals by owner"),Cat8)
classifier.Learn(toSlice("vw atlas"),Cat8)
classifier.Learn(toSlice("vw tiguan"),Cat8)
classifier.Learn(toSlice("carhartt clothing"),Cat9)
classifier.Learn(toSlice("engagement rings for women"),Cat9)
classifier.Learn(toSlice("figs scrubs"),Cat9)
classifier.Learn(toSlice("italo jewelry"),Cat9)
classifier.Learn(toSlice("jewelry stores"),Cat9)
classifier.Learn(toSlice("jockey underwear for women"),Cat9)
classifier.Learn(toSlice("koi scrubs"),Cat9)
classifier.Learn(toSlice("men's slippers"),Cat9)
classifier.Learn(toSlice("men's walking shoes"),Cat9)
classifier.Learn(toSlice("mens slippers"),Cat9)
classifier.Learn(toSlice("merrell shoes"),Cat9)
classifier.Learn(toSlice("merrell shoes for women"),Cat9)
classifier.Learn(toSlice("miraclesuit swimwear"),Cat9)
classifier.Learn(toSlice("new balance sneakers"),Cat9)
classifier.Learn(toSlice("rings"),Cat9)
classifier.Learn(toSlice("ross simons catalog jewelry"),Cat9)
classifier.Learn(toSlice("scrubs uniforms"),Cat9)
classifier.Learn(toSlice("socks"),Cat9)
classifier.Learn(toSlice("sorrells boots"),Cat9)
classifier.Learn(toSlice("sunglasses for men"),Cat9)
classifier.Learn(toSlice("t-shirt design"),Cat9)
classifier.Learn(toSlice("free plagiarism checker"),Cat10)
classifier.Learn(toSlice("aero trainer reviews"),Cat11)
classifier.Learn(toSlice("airline tickets best price"),Cat11)
classifier.Learn(toSlice("audio books"),Cat11)
classifier.Learn(toSlice("chiefs gear"),Cat11)
classifier.Learn(toSlice("echelon bike"),Cat11)
classifier.Learn(toSlice("elliptical"),Cat11)
classifier.Learn(toSlice("elliptical exercise machine"),Cat11)
classifier.Learn(toSlice("exercise bikes"),Cat11)
classifier.Learn(toSlice("nordictrack elliptical"),Cat11)
classifier.Learn(toSlice("peloton treadmill"),Cat11)
classifier.Learn(toSlice("proform treadmill"),Cat11)
classifier.Learn(toSlice("recumbent exercise bikes"),Cat11)
classifier.Learn(toSlice("silk pillowcases"),Cat11)
classifier.Learn(toSlice("treadmill reviews"),Cat11)
classifier.Learn(toSlice("treadmills"),Cat11)
classifier.Learn(toSlice("birthday cake delivery"),Cat12)
classifier.Learn(toSlice("chocolate covered strawberries"),Cat12)
classifier.Learn(toSlice("chocolate covered strawberries delivered"),Cat12)
classifier.Learn(toSlice("freeze dried food"),Cat12)
classifier.Learn(toSlice("freshly food delivery"),Cat12)
classifier.Learn(toSlice("fruit basket delivery"),Cat12)
classifier.Learn(toSlice("fruit baskets delivered"),Cat12)
classifier.Learn(toSlice("fruit baskets edible arrangements"),Cat12)
classifier.Learn(toSlice("fruit bouquets"),Cat12)
classifier.Learn(toSlice("kind bars"),Cat12)
classifier.Learn(toSlice("kroger online shopping"),Cat12)
classifier.Learn(toSlice("postmates delivery"),Cat12)
classifier.Learn(toSlice("bridesmaid dresses"),Cat13)
classifier.Learn(toSlice("brighton jewelry"),Cat13)
classifier.Learn(toSlice("dyson air purifier"),Cat13)
classifier.Learn(toSlice("ecards"),Cat13)
classifier.Learn(toSlice("edible arrangements"),Cat13)
classifier.Learn(toSlice("edible arrangements promotional code "),Cat13)
classifier.Learn(toSlice("funeral flowers"),Cat13)
classifier.Learn(toSlice("graphic design software"),Cat13)
classifier.Learn(toSlice("greeting cards"),Cat13)
classifier.Learn(toSlice("internet providers by zip code"),Cat13)
classifier.Learn(toSlice("internet service providers by zip code"),Cat13)
classifier.Learn(toSlice("lab grown diamonds"),Cat13)
classifier.Learn(toSlice("patriot foods emergency food"),Cat13)
classifier.Learn(toSlice("restaurant supply"),Cat13)
classifier.Learn(toSlice("t-mobile plans"),Cat13)
classifier.Learn(toSlice("womens slippers"),Cat13)
classifier.Learn(toSlice("bali bras"),Cat19)
classifier.Learn(toSlice("best collagen powder"),Cat19)
classifier.Learn(toSlice("best eyelash growth product"),Cat19)
classifier.Learn(toSlice("collagen supplement"),Cat19)
classifier.Learn(toSlice("crepe erase skin care"),Cat19)
classifier.Learn(toSlice("estee lauder cosmetics"),Cat19)
classifier.Learn(toSlice("eyelash growth serum"),Cat19) 
classifier.Learn(toSlice("moroccan oil hair product"),Cat19)
classifier.Learn(toSlice("nioxin hair products"),Cat19)
classifier.Learn(toSlice("obagi skin care"),Cat19)
classifier.Learn(toSlice("thrive mascara"),Cat19)

classifier.ConvertTermsFreqToTfIdf()


scores, likely, _ := classifier.LogScores(
                        toSlice(search),
                     )

fmt.Println(scores)
fmt.Println(likely)
fmt.Println(classifier.Classes[likely])

}
